/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as MapRouteImport } from './routes/map'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityCityNameRouteImport } from './routes/city.$cityName'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityNameRoute = CityCityNameRouteImport.update({
  id: '/city/$cityName',
  path: '/city/$cityName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/map': typeof MapRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/city/$cityName': typeof CityCityNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/map': typeof MapRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/city/$cityName': typeof CityCityNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/map': typeof MapRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/city/$cityName': typeof CityCityNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/map'
    | '/rankings'
    | '/search'
    | '/city/$cityName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/map' | '/rankings' | '/search' | '/city/$cityName'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/map'
    | '/rankings'
    | '/search'
    | '/city/$cityName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  MapRoute: typeof MapRoute
  RankingsRoute: typeof RankingsRoute
  SearchRoute: typeof SearchRoute
  CityCityNameRoute: typeof CityCityNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityName': {
      id: '/city/$cityName'
      path: '/city/$cityName'
      fullPath: '/city/$cityName'
      preLoaderRoute: typeof CityCityNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  MapRoute: MapRoute,
  RankingsRoute: RankingsRoute,
  SearchRoute: SearchRoute,
  CityCityNameRoute: CityCityNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
